#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

protectedBranches="master production"
for i in ${protectedBranches}
do
    currentBranch=$(git rev-parse --abbrev-ref HEAD)
    if [ "$i" = "$currentBranch" ] ; then
        RED='\033[0;31m'
        NC='\033[0m'
        echo "${RED}ERROR: You cannot push directly to the $currentBranch branch${NC}"
        exit 1
    fi
done
